# Generated by Django 4.0.4 on 2022-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ReminderTime',
            field=models.DateTimeField(default='1:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default='2022-04-30 23:59:59.999999+00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default='2022-04-30 14:25:24.418428+00:00'),
        ),
    ]
