# Generated by Django 4.0.4 on 2022-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_address', models.EmailField(blank=True, default=None, max_length=60, unique=True, verbose_name='email')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
    ]
